#test:
#  prop: testValue
#
#testcase:
#  book:
#    id: ${random.int}


server:
  port: 80
spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:~/test
    hikari:
      driver-class-name: org.h2.Driver
      username: sa
      password: 123456
